namespace ScreenBux.Data.Entities;

/// <summary>
/// A controlled device linked to a parent account (and optionally a child profile).
/// </summary>
public class Device
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public string AccountId { get; set; } = string.Empty;

    public Account? Account { get; set; }

    public Guid? ChildProfileId { get; set; }

    public ChildProfile? ChildProfile { get; set; }

    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Stable per-machine key generated by the Service on first run.
    /// </summary>
    public string MachineKey { get; set; } = string.Empty;

    public DateTime LinkedAt { get; set; } = DateTime.UtcNow;

    public DateTime? LastSeenAt { get; set; }
}
